version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management console port
    environment:
      RABBITMQ_DEFAULT_USER: guest  # Default username
      RABBITMQ_DEFAULT_PASS: guest  # Default password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist data

  redis:
    image: redis:7.2.4
    container_name: ormus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  etcd:
    image: quay.io/coreos/etcd:v3.5.13
    container_name: etcd
    command: /usr/local/bin/etcd -name etcd0 -advertise-client-urls http://etcd:2379 -listen-client-urls http://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/etcd-data

  scylladb:
    image: scylladb/scylla:latest
    container_name: scylladb
    restart: always
    ports:
      - "9042:9042"
volumes:
  redis_data:
  etcd_data:
  rabbitmq_data: