version: '3.8'
services:
  #Destination Service
  destination_webhook_worker:
    build:
      context: .
      dockerfile: go/destination/webhook_worker/Dockerfile
      args:
        GO_IMAGE_NAME: ${GO_IMAGE_NAME}
        GO_IMAGE_VERSION: ${GO_IMAGE_VERSION}
    image: ormus-destination-webhook-worker:${GO_IMAGE_VERSION}
    container_name: "ormus-destination-webhook-worker"
    entrypoint:
      - air
      - "-c"
      - /home/app/serve/docker-compose/services/go/destination/webhook_worker/.destination.air.toml
    volumes:
      - ../../../:/home/app
    depends_on:
      - otel_collector
      - redis
      - rabbitmq
      - etcd
    environment:
      ORMUS_DESTINATION__RABBITMQ_CONSUMER_CONNECTION__HOST: rabbitmq
      ORMUS_DESTINATION__RABBITMQ_TASK_MANAGER_CONNECTION__HOST: rabbitmq
      ORMUS_DESTINATION__REDIS_TASK_IDEMPOTENCY__HOST: redis
      ORMUS_REDIS__HOST: redis
      ORMUS_ETCD__HOST: etcd


